apiVersion: v1
kind: Pod 
metadata: 
  name: podc
  namespace: media-wiki
  labels: 
    app: mediawikiapp  
spec:
  containers: # List
    - name: media-wiki
      image: mediawiki
      imagePullPolicy: Always
      ports:
          - containerPort: 80
          # Requests & Limits   
      resources:
            requests:
              cpu: "100m" 
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "400Mi"                     
              
