apiVersion: v1
kind: Service 
metadata:
  name: mediawiki-pod-service
  namespace: media-wiki
spec:
  type: LoadBalancer 
  selector:
    app: mediawikiapp
  ports: 
    - name: http
      port: 80 
      targetPort: 80 