apiVersion: v1
kind: Namespace
metadata:
   name: media-wiki

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ns-resource-quota
  namespace: media-wiki
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi  
    pods: "5"    
    configmaps: "5" 
    persistentvolumeclaims: "5" 
    secrets: "5" 
    services: "5" 
