apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-wiki-mysql-pv-claim
  namespace: media-wiki
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
