apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-wiki-mysql
  namespace: media-wiki
spec:
  selector:
    matchLabels:
      app: media-wiki-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: media-wiki-mysql
    spec:
      containers:
        - image: mysql:8.0
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: media-wiki-mysql-pv-claim
